In [1]:
###########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [ ]:
import tensorflow as tf
import pandas as pd

In [2]:
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [3]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

In [5]:
아이리스.columns

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')

In [6]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [7]:
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [ ]:
X = tf.keras.layers.Input(shape=[4])
y = tf.keras.layers.Dense(3, activation='softmax')(X)
model = tf.keras.models.Model(X, y)
model.compile(loss='categorical_crossentropy',
             metrics='accuracy')

In [8]:
###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000, verbose=0)

Epoch 1/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1685 - accuracy: 0.9667
Epoch 2/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1685 - accuracy: 0.9600
Epoch 3/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1687 - accuracy: 0.9667
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1679 - accuracy: 0.9667
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1686 - accuracy: 0.9667
Epoch 6/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1676 - accuracy: 0.9667
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1677 - accuracy: 0.9667
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1675 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1672 - accuracy: 0.9600
Epoch 10/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1678 - accuracy: 0.9667


In [11]:
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 997us/step - loss: 0.1522 - accuracy: 0.9667
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1524 - accuracy: 0.9600
Epoch 3/100
5/5 [==============================] - 0s 998us/step - loss: 0.1524 - accuracy: 0.9667
Epoch 4/100
5/5 [==============================] - 0s 997us/step - loss: 0.1521 - accuracy: 0.9667
Epoch 5/100
5/5 [==============================] - 0s 499us/step - loss: 0.1521 - accuracy: 0.9667
Epoch 6/100
5/5 [==============================] - 0s 748us/step - loss: 0.1526 - accuracy: 0.9667
Epoch 7/100
5/5 [==============================] - 0s 746us/step - loss: 0.1518 - accuracy: 0.9667
Epoch 8/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1517 - accuracy: 0.9667
Epoch 9/100
5/5 [==============================] - 0s 994us/step - loss: 0.1521 - accuracy: 0.9667
Epoch 10/100
5/5 [==============================] - 0s 740us/step - loss: 0.1519 - accuracy: 0.9667
Epoch 11/100


5/5 [==============================] - 0s 748us/step - loss: 0.1446 - accuracy: 0.9667
Epoch 83/100
5/5 [==============================] - 0s 748us/step - loss: 0.1437 - accuracy: 0.9667
Epoch 84/100
5/5 [==============================] - 0s 997us/step - loss: 0.1440 - accuracy: 0.9667
Epoch 85/100
5/5 [==============================] - 0s 997us/step - loss: 0.1439 - accuracy: 0.9667
Epoch 86/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1438 - accuracy: 0.9667
Epoch 87/100
5/5 [==============================] - 0s 748us/step - loss: 0.1434 - accuracy: 0.9667
Epoch 88/100
5/5 [==============================] - 0s 499us/step - loss: 0.1436 - accuracy: 0.9600
Epoch 89/100
5/5 [==============================] - 0s 998us/step - loss: 0.1437 - accuracy: 0.9667
Epoch 90/100
5/5 [==============================] - 0s 748us/step - loss: 0.1431 - accuracy: 0.9667
Epoch 91/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1435 - accuracy: 0.9667
Epoch 92/100
5/5 

In [12]:
###########################
# 4. 모델을 이용합니다
# 맨 처음 데이터 5개
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9946755e-01 5.3248531e-04 1.3243922e-08]
 [9.9823260e-01 1.7673023e-03 1.2593239e-07]
 [9.9898618e-01 1.0137883e-03 5.0584084e-08]
 [9.9689853e-01 3.1012497e-03 2.5388428e-07]
 [9.9950635e-01 4.9360591e-04 1.0920978e-08]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [13]:
# 맨 마지막 데이터 5개
print(model.predict(독립[-5:]))
print(종속[-5:])

[[1.15009115e-07 7.38802254e-02 9.26119685e-01]
 [3.93792135e-07 1.38749763e-01 8.61249864e-01]
 [5.97015514e-07 1.93283573e-01 8.06715846e-01]
 [7.12225088e-08 8.53525773e-02 9.14647400e-01]
 [1.23513382e-06 2.92151481e-01 7.07847238e-01]]
     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [14]:
###########################
# weights & bias 출력
print(model.get_weights())

[array([[ 1.0485132 , -0.12520804, -0.7928931 ],
       [ 2.924284  ,  0.99199086, -0.84604174],
       [-4.3134108 , -0.26540256,  0.95739657],
       [-4.9312    , -1.8646547 ,  2.2462857 ]], dtype=float32), array([ 2.3315017,  1.2625626, -2.0350091], dtype=float32)]
