In [1]:
##########################
# 라이브러리 사용
import tensorflow as tf
import pandas as pd

In [2]:
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)
 
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [3]:
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')
 
# 모델 구조 확인
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [8]:
###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=1000)

Epoch 1/1000
16/16 [==============================] - 0s 598us/step - loss: 29.6144
Epoch 2/1000
16/16 [==============================] - 0s 666us/step - loss: 31.7739
Epoch 3/1000
16/16 [==============================] - 0s 532us/step - loss: 28.7990
Epoch 4/1000
16/16 [==============================] - 0s 532us/step - loss: 29.7373
Epoch 5/1000
16/16 [==============================] - 0s 665us/step - loss: 28.5315
Epoch 6/1000
16/16 [==============================] - 0s 598us/step - loss: 30.3834
Epoch 7/1000
16/16 [==============================] - 0s 598us/step - loss: 32.2332
Epoch 8/1000
16/16 [==============================] - 0s 598us/step - loss: 28.9202
Epoch 9/1000
16/16 [==============================] - 0s 598us/step - loss: 29.7865
Epoch 10/1000
16/16 [==============================] - 0s 598us/step - loss: 29.4415
Epoch 11/1000
16/16 [==============================] - 0s 598us/step - loss: 30.0110
Epoch 12/1000
16/16 [==============================] - 0s 598us/step - los

16/16 [==============================] - 0s 665us/step - loss: 29.0144
Epoch 98/1000
16/16 [==============================] - 0s 665us/step - loss: 28.0433
Epoch 99/1000
16/16 [==============================] - 0s 798us/step - loss: 28.5563
Epoch 100/1000
16/16 [==============================] - 0s 864us/step - loss: 30.6168
Epoch 101/1000
16/16 [==============================] - 0s 665us/step - loss: 27.7141
Epoch 102/1000
16/16 [==============================] - 0s 598us/step - loss: 29.0486
Epoch 103/1000
16/16 [==============================] - 0s 731us/step - loss: 29.5021
Epoch 104/1000
16/16 [==============================] - 0s 864us/step - loss: 28.3801
Epoch 105/1000
16/16 [==============================] - 0s 864us/step - loss: 28.3027
Epoch 106/1000
16/16 [==============================] - 0s 731us/step - loss: 28.1408
Epoch 107/1000
16/16 [==============================] - 0s 532us/step - loss: 30.7532
Epoch 108/1000
16/16 [==============================] - 0s 598us/step -

16/16 [==============================] - 0s 598us/step - loss: 27.3377
Epoch 193/1000
16/16 [==============================] - 0s 532us/step - loss: 29.5967
Epoch 194/1000
16/16 [==============================] - 0s 599us/step - loss: 27.3184
Epoch 195/1000
16/16 [==============================] - 0s 599us/step - loss: 28.0859
Epoch 196/1000
16/16 [==============================] - 0s 465us/step - loss: 27.7828
Epoch 197/1000
16/16 [==============================] - 0s 598us/step - loss: 28.6973
Epoch 198/1000
16/16 [==============================] - 0s 532us/step - loss: 27.7179
Epoch 199/1000
16/16 [==============================] - 0s 532us/step - loss: 28.0251
Epoch 200/1000
16/16 [==============================] - 0s 598us/step - loss: 27.8620
Epoch 201/1000
16/16 [==============================] - 0s 465us/step - loss: 26.5560
Epoch 202/1000
16/16 [==============================] - 0s 598us/step - loss: 27.6242
Epoch 203/1000
16/16 [==============================] - 0s 534us/step

16/16 [==============================] - 0s 532us/step - loss: 26.3783
Epoch 288/1000
16/16 [==============================] - 0s 465us/step - loss: 27.7791
Epoch 289/1000
16/16 [==============================] - 0s 532us/step - loss: 26.7770
Epoch 290/1000
16/16 [==============================] - 0s 584us/step - loss: 26.2842
Epoch 291/1000
16/16 [==============================] - 0s 464us/step - loss: 26.5374
Epoch 292/1000
16/16 [==============================] - 0s 665us/step - loss: 26.9557
Epoch 293/1000
16/16 [==============================] - 0s 465us/step - loss: 27.5486
Epoch 294/1000
16/16 [==============================] - 0s 532us/step - loss: 25.1457
Epoch 295/1000
16/16 [==============================] - 0s 532us/step - loss: 28.5970
Epoch 296/1000
16/16 [==============================] - 0s 532us/step - loss: 26.2117
Epoch 297/1000
16/16 [==============================] - 0s 598us/step - loss: 27.2636
Epoch 298/1000
16/16 [==============================] - 0s 465us/step

16/16 [==============================] - 0s 532us/step - loss: 26.6489
Epoch 383/1000
16/16 [==============================] - 0s 532us/step - loss: 27.1356
Epoch 384/1000
16/16 [==============================] - 0s 532us/step - loss: 24.3016
Epoch 385/1000
16/16 [==============================] - 0s 465us/step - loss: 29.1015
Epoch 386/1000
16/16 [==============================] - 0s 665us/step - loss: 27.3720
Epoch 387/1000
16/16 [==============================] - 0s 599us/step - loss: 26.9090
Epoch 388/1000
16/16 [==============================] - 0s 465us/step - loss: 25.8650
Epoch 389/1000
16/16 [==============================] - 0s 598us/step - loss: 26.7793
Epoch 390/1000
16/16 [==============================] - 0s 465us/step - loss: 26.5280
Epoch 391/1000
16/16 [==============================] - 0s 598us/step - loss: 27.8982
Epoch 392/1000
16/16 [==============================] - 0s 731us/step - loss: 25.4234
Epoch 393/1000
16/16 [==============================] - 0s 665us/step

16/16 [==============================] - 0s 598us/step - loss: 26.7185
Epoch 478/1000
16/16 [==============================] - 0s 532us/step - loss: 27.0915
Epoch 479/1000
16/16 [==============================] - 0s 598us/step - loss: 25.0616
Epoch 480/1000
16/16 [==============================] - 0s 599us/step - loss: 27.3926
Epoch 481/1000
16/16 [==============================] - 0s 465us/step - loss: 27.0184
Epoch 482/1000
16/16 [==============================] - 0s 598us/step - loss: 27.0681
Epoch 483/1000
16/16 [==============================] - 0s 465us/step - loss: 24.9393
Epoch 484/1000
16/16 [==============================] - 0s 598us/step - loss: 27.5212
Epoch 485/1000
16/16 [==============================] - 0s 598us/step - loss: 25.7631
Epoch 486/1000
16/16 [==============================] - 0s 466us/step - loss: 26.2005
Epoch 487/1000
16/16 [==============================] - 0s 598us/step - loss: 27.3344
Epoch 488/1000
16/16 [==============================] - 0s 532us/step

16/16 [==============================] - 0s 598us/step - loss: 26.0303
Epoch 573/1000
16/16 [==============================] - 0s 532us/step - loss: 26.8489
Epoch 574/1000
16/16 [==============================] - 0s 532us/step - loss: 25.7035
Epoch 575/1000
16/16 [==============================] - 0s 598us/step - loss: 26.1205
Epoch 576/1000
16/16 [==============================] - 0s 466us/step - loss: 25.6056
Epoch 577/1000
16/16 [==============================] - 0s 532us/step - loss: 25.2765
Epoch 578/1000
16/16 [==============================] - 0s 666us/step - loss: 24.9908
Epoch 579/1000
16/16 [==============================] - 0s 465us/step - loss: 26.6471
Epoch 580/1000
16/16 [==============================] - 0s 598us/step - loss: 25.9873
Epoch 581/1000
16/16 [==============================] - 0s 598us/step - loss: 28.5437
Epoch 582/1000
16/16 [==============================] - 0s 532us/step - loss: 24.0967
Epoch 583/1000
16/16 [==============================] - 0s 665us/step

16/16 [==============================] - 0s 532us/step - loss: 27.4048
Epoch 668/1000
16/16 [==============================] - 0s 532us/step - loss: 24.2560
Epoch 669/1000
16/16 [==============================] - 0s 598us/step - loss: 25.2946
Epoch 670/1000
16/16 [==============================] - 0s 598us/step - loss: 23.7578
Epoch 671/1000
16/16 [==============================] - 0s 532us/step - loss: 26.1379
Epoch 672/1000
16/16 [==============================] - 0s 598us/step - loss: 26.1096
Epoch 673/1000
16/16 [==============================] - 0s 532us/step - loss: 25.6074
Epoch 674/1000
16/16 [==============================] - 0s 532us/step - loss: 24.3984
Epoch 675/1000
16/16 [==============================] - 0s 598us/step - loss: 23.5414
Epoch 676/1000
16/16 [==============================] - 0s 465us/step - loss: 26.6010
Epoch 677/1000
16/16 [==============================] - 0s 665us/step - loss: 26.1395
Epoch 678/1000
16/16 [==============================] - 0s 665us/step

16/16 [==============================] - 0s 798us/step - loss: 23.7006
Epoch 763/1000
16/16 [==============================] - 0s 731us/step - loss: 24.6929
Epoch 764/1000
16/16 [==============================] - 0s 465us/step - loss: 24.7886
Epoch 765/1000
16/16 [==============================] - 0s 598us/step - loss: 24.3828
Epoch 766/1000
16/16 [==============================] - 0s 798us/step - loss: 24.3348
Epoch 767/1000
16/16 [==============================] - 0s 665us/step - loss: 25.6153
Epoch 768/1000
16/16 [==============================] - 0s 532us/step - loss: 23.5861
Epoch 769/1000
16/16 [==============================] - 0s 598us/step - loss: 25.0819
Epoch 770/1000
16/16 [==============================] - 0s 598us/step - loss: 24.1175
Epoch 771/1000
16/16 [==============================] - 0s 465us/step - loss: 24.9200
Epoch 772/1000
16/16 [==============================] - 0s 665us/step - loss: 25.9289
Epoch 773/1000
16/16 [==============================] - 0s 598us/step

16/16 [==============================] - 0s 532us/step - loss: 24.3564
Epoch 858/1000
16/16 [==============================] - 0s 598us/step - loss: 23.9241
Epoch 859/1000
16/16 [==============================] - 0s 665us/step - loss: 24.7977
Epoch 860/1000
16/16 [==============================] - 0s 599us/step - loss: 24.5558
Epoch 861/1000
16/16 [==============================] - 0s 598us/step - loss: 24.7602
Epoch 862/1000
16/16 [==============================] - 0s 665us/step - loss: 24.1863
Epoch 863/1000
16/16 [==============================] - 0s 665us/step - loss: 25.8960
Epoch 864/1000
16/16 [==============================] - 0s 532us/step - loss: 24.6555
Epoch 865/1000
16/16 [==============================] - 0s 666us/step - loss: 24.2690
Epoch 866/1000
16/16 [==============================] - 0s 598us/step - loss: 24.5105
Epoch 867/1000
16/16 [==============================] - 0s 465us/step - loss: 25.0634
Epoch 868/1000
16/16 [==============================] - 0s 665us/step

16/16 [==============================] - 0s 532us/step - loss: 22.8608
Epoch 953/1000
16/16 [==============================] - 0s 665us/step - loss: 23.7055
Epoch 954/1000
16/16 [==============================] - 0s 532us/step - loss: 23.1733
Epoch 955/1000
16/16 [==============================] - 0s 465us/step - loss: 25.8301
Epoch 956/1000
16/16 [==============================] - 0s 598us/step - loss: 24.3191
Epoch 957/1000
16/16 [==============================] - 0s 465us/step - loss: 23.7977
Epoch 958/1000
16/16 [==============================] - 0s 532us/step - loss: 26.0607
Epoch 959/1000
16/16 [==============================] - 0s 532us/step - loss: 23.8921
Epoch 960/1000
16/16 [==============================] - 0s 465us/step - loss: 24.3684
Epoch 961/1000
16/16 [==============================] - 0s 665us/step - loss: 25.0013
Epoch 962/1000
16/16 [==============================] - 0s 465us/step - loss: 22.6787
Epoch 963/1000
16/16 [==============================] - 0s 598us/step

In [9]:
###########################
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[29.833664]
 [24.374681]
 [29.876358]
 [29.246538]
 [28.619432]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [10]:
###########################
# 모델의 수식 확인
print(model.get_weights())

[array([[ 5.4836810e-01,  7.5690418e-01,  3.3075458e-01,  3.4811550e-01,
         1.5534386e-01, -1.0516105e-01, -1.3540109e-01,  4.7399122e-02,
        -2.8184464e-04, -5.4166931e-01],
       [ 5.2945632e-01,  6.3528991e-03, -4.4696352e-01, -4.2128316e-01,
         5.4626751e-01, -3.1920552e-01,  2.1758731e-01, -2.7476111e-01,
        -9.7570501e-02,  1.4492826e-01],
       [-3.3423847e-01, -2.5201336e-01, -1.3229540e-01, -6.0408674e-02,
         7.0996845e-01,  3.1974831e-01, -4.0338603e-01,  4.8395172e-01,
         3.3749866e-01, -1.1972142e-01],
       [-1.1587809e+00,  9.2502612e-01,  2.0985776e-01, -2.1309092e+00,
         2.4299593e+00, -9.3304086e-01,  1.0251403e+00,  1.1675785e+00,
        -1.2158788e+00,  4.9478608e-01],
       [ 3.5770881e-01,  1.2837386e-01,  1.8392849e-01,  8.3780360e-01,
        -4.8842454e-01, -5.3534979e-01, -3.6877552e-01,  4.8193878e-01,
        -4.7440401e-01, -3.3786741e-01],
       [-1.4828697e+00, -2.5955713e-01, -1.2295917e-01,  1.1262369e+00,
  

In [11]:
###########################
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
 
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
 
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [12]:
###########################
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')
 
# 모델 구조 확인
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [13]:
###########################
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 748us/step - loss: 1.0872 - accuracy: 0.6758
Epoch 2/100
5/5 [==============================] - 0s 1ms/step - loss: 1.0579 - accuracy: 0.6888
Epoch 3/100
5/5 [==============================] - 0s 748us/step - loss: 1.0593 - accuracy: 0.6237
Epoch 4/100
5/5 [==============================] - 0s 1ms/step - loss: 1.0370 - accuracy: 0.6793
Epoch 5/100
5/5 [==============================] - 0s 996us/step - loss: 1.0242 - accuracy: 0.6840
Epoch 6/100
5/5 [==============================] - 0s 997us/step - loss: 1.0098 - accuracy: 0.6910
Epoch 7/100
5/5 [==============================] - 0s 1ms/step - loss: 0.9952 - accuracy: 0.6736
Epoch 8/100
5/5 [==============================] - 0s 1ms/step - loss: 0.9924 - accuracy: 0.6432
Epoch 9/100
5/5 [==============================] - 0s 998us/step - loss: 0.9725 - accuracy: 0.6462
Epoch 10/100
5/5 [==============================] - 0s 734us/step - loss: 0.9522 - accuracy: 0.6857
Epoch 11/100
5/5 

5/5 [==============================] - 0s 996us/step - loss: 0.1088 - accuracy: 0.9720
Epoch 84/100
5/5 [==============================] - 0s 748us/step - loss: 0.1017 - accuracy: 0.9824
Epoch 85/100
5/5 [==============================] - 0s 997us/step - loss: 0.0944 - accuracy: 0.9767
Epoch 86/100
5/5 [==============================] - 0s 748us/step - loss: 0.1338 - accuracy: 0.9441
Epoch 87/100
5/5 [==============================] - 0s 1ms/step - loss: 0.0920 - accuracy: 0.9733
Epoch 88/100
5/5 [==============================] - 0s 748us/step - loss: 0.1134 - accuracy: 0.9625
Epoch 89/100
5/5 [==============================] - 0s 748us/step - loss: 0.1050 - accuracy: 0.9637
Epoch 90/100
5/5 [==============================] - 0s 996us/step - loss: 0.1050 - accuracy: 0.9637
Epoch 91/100
5/5 [==============================] - 0s 748us/step - loss: 0.0898 - accuracy: 0.9907
Epoch 92/100
5/5 [==============================] - 0s 748us/step - loss: 0.0942 - accuracy: 0.9768
Epoch 93/100
5/

In [14]:
###########################
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9817884e-01 1.8208958e-03 1.9133728e-07]
 [9.9529845e-01 4.7007441e-03 7.9729858e-07]
 [9.9696857e-01 3.0310308e-03 5.1142325e-07]
 [9.9422437e-01 5.7746479e-03 9.7115696e-07]
 [9.9837625e-01 1.6235634e-03 1.6570446e-07]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
